name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Small
      run: >
        dotnet publish -c release -p:PublishDir=../dist/small --no-self-contained 
        -p:PublishSingleFile=true -p:DebugType=embedded -p:PublishTrimmed=false 
        -p:EnableCompressionInSingleFile=false --use-current-runtime
    - name: Portable
      run: >
        dotnet publish -c release -p:PublishDir=../dist/portable --self-contained 
        -p:PublishSingleFile=true -p:DebugType=embedded -p:PublishTrimmed=true -p:TrimMode=partial
        -p:EnableCompressionInSingleFile=true --use-current-runtime
    - uses: actions/upload-artifact@v3
      with:
        name: ElsParsers-${{ matrix.os }}
        path: ${{ github.workspace }}/dist/small

    - uses: actions/upload-artifact@v3
      with:
        name: ElsParsers-${{ matrix.os }}-portable
        path: ${{ github.workspace }}/dist/portable
    
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: download-artifact-ubuntu
        if: ${{ steps.last_release.outputs.tag_name != steps.get-version.outputs.version }}
        uses: actions/download-artifact@v3
        with:
          name: ElsParsers-ubuntu-latest
          path: ${{ github.workspace }}/linux
      - name: download-artifact-ubuntu-portable
        if: ${{ steps.last_release.outputs.tag_name != steps.get-version.outputs.version }}
        uses: actions/download-artifact@v3
        with:
          name: ElsParsers-ubuntu-latest-portable
          path: ${{ github.workspace }}/linux-portable      
          
      - name: download-artifact-windows
        if: ${{ steps.last_release.outputs.tag_name != steps.get-version.outputs.version }}
        uses: actions/download-artifact@v3
        with:
          name: ElsParsers-windows-latest
          path: ${{ github.workspace }}/windows
      - name: download-artifact-windows-portable
        if: ${{ steps.last_release.outputs.tag_name != steps.get-version.outputs.version }}
        uses: actions/download-artifact@v3
        with:
          name: ElsParsers-windows-latest-portable
          path: ${{ github.workspace }}/windows-portable
          
      - name: download-artifact-macos
        if: ${{ steps.last_release.outputs.tag_name != steps.get-version.outputs.version }}
        uses: actions/download-artifact@v3
        with:
          name: ElsParsers-macos-latest
          path: ${{ github.workspace }}/macos
      - name: download-artifact-macos-portable
        if: ${{ steps.last_release.outputs.tag_name != steps.get-version.outputs.version }}
        uses: actions/download-artifact@v3
        with:
          name: ElsParsers-macos-latest-portable
          path: ${{ github.workspace }}/macos-portable
